In [1]:
import pandas as pd
import numpy as np

In [2]:
interactions_example = pd.DataFrame([
    {
        "user_id": 1,
        "item_id": 0
    },
    {
        "user_id": 2,
        "item_id": 0
    },
    {
        "user_id": 1,
        "item_id": 4
    },
    {
        "user_id": 1,
        "item_id": 1
    },
    {
        "user_id": 3,
        "item_id": 4
    },
    {
        "user_id": 2,
        "item_id": 1
    },
    {
        "user_id": 4,
        "item_id": 0
    },
    {
        "user_id": 5,
        "item_id": 4
    },
    {
        "user_id": 2,
        "item_id": 4
    },
    {
        "user_id": 4,
        "item_id": 4
    },
    {
        "user_id": 4,
        "item_id": 2
    }
])
interactions_example

user_id  item_id
0         1        0
1         2        0
2         1        4
3         1        1
4         3        4
5         2        1
6         4        0
7         5        4
8         2        4
9         4        4
10        4        2

In [3]:
items_embeddings = [
    [1, 1, 1, 1, 1],
    [2, 2, 2, 2, 2],
    [3, 3, 3, 3, 3],
    [4, 4, 4, 4, 4],
    [5, 5, 5, 5, 5]
]
items_embeddings

[[1, 1, 1, 1, 1],
 [2, 2, 2, 2, 2],
 [3, 3, 3, 3, 3],
 [4, 4, 4, 4, 4],
 [5, 5, 5, 5, 5]]

In [4]:
items_embeddings = np.array(items_embeddings)

In [5]:
users_current_info = {}
contexts = []

for i, row in interactions_example.iterrows():
    user_id = row["user_id"]
    item_id = row["item_id"]

    if user_id not in users_current_info:
        users_current_info[user_id] = {
            'acum_emb': np.array([0, 0, 0, 0, 0]),
            'count': 0
        }
    
    contexts.append(users_current_info[user_id]['acum_emb'] / max(1, users_current_info[user_id]['count']))

    users_current_info[user_id]['acum_emb'] += items_embeddings[item_id]
    users_current_info[user_id]['count'] += 1

contexts

[array([0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]),
 array([3., 3., 3., 3., 3.]),
 array([0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0.]),
 array([1.5, 1.5, 1.5, 1.5, 1.5]),
 array([1., 1., 1., 1., 1.]),
 array([3., 3., 3., 3., 3.])]

In [6]:
interactions_example['context'] = contexts
interactions_example

user_id  item_id                    context
0         1        0  [0.0, 0.0, 0.0, 0.0, 0.0]
1         2        0  [0.0, 0.0, 0.0, 0.0, 0.0]
2         1        4  [1.0, 1.0, 1.0, 1.0, 1.0]
3         1        1  [3.0, 3.0, 3.0, 3.0, 3.0]
4         3        4  [0.0, 0.0, 0.0, 0.0, 0.0]
5         2        1  [1.0, 1.0, 1.0, 1.0, 1.0]
6         4        0  [0.0, 0.0, 0.0, 0.0, 0.0]
7         5        4  [0.0, 0.0, 0.0, 0.0, 0.0]
8         2        4  [1.5, 1.5, 1.5, 1.5, 1.5]
9         4        4  [1.0, 1.0, 1.0, 1.0, 1.0]
10        4        2  [3.0, 3.0, 3.0, 3.0, 3.0]